### ISSUE TITLE
Cannot create database diagram (stackoverflow db, 1gig version)

### ISSUE THREAD

**Issue by Bobobaal** [vertonghenb/DBII-Workshops#18]
![image](https://user-images.githubusercontent.com/15947020/57683386-d0ccc080-7633-11e9-89b3-c7a371d2581a.png)

**Comment by vertonghenb** [comment]
Due to the ownershop of the database:
Run the following command to change ownership:
```sql
    use [StackOverflow2010] EXEC sp_changedbowner 'sa'
```
