### ISSUE TITLE
Repeatable Read - Select(count(*))

### ISSUE THREAD

**Issue by BertHG** [vertonghenb/DBII-Workshops#24]
Is there a problem when you execute a select(count(*)) during a repeatable read  while another transactions is inserting a new row.

**Comment by vertonghenb** [comment]
Yes, you can try to execute the following code:
### Session 1
```sql
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
SET NOCOUNT ON
GO
BEGIN TRANSACTION
SELECT  Count(*)
FROM    dbo.TestIsolationLevels 
WAITFOR DELAY '00:00:10'
SELECT  Count(*)
FROM    dbo.TestIsolationLevels 
COMMIT
```

### Session 2
```sql
BEGIN TRANSACTION
INSERT INTO dbo.TestIsolationLevels 
VALUES (999, 'Phantom Employee 2', 30000)
COMMIT
```

### Flow:
1. Session 1 does the count
2. Session 2 is allowed to insert a new row (repeatable read)
3. Session 1 does the count again but has a different value

### Solution
Use a `SERIALIZABLE` transaction if you do not want other transactions to insert rows while you're processing your count(*)
